version: '3.8'

services:
  web:
    build: .
    ports:
      - 5000:5000
    environment:
      HOST: mongodb://database:27017/

  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - myvol:/data/db

volumes:
  myvol:
